// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TimeTableScheduler.Repository.Entities
{
    public partial class Class
    {
        public Class()
        {
            Subject = new HashSet<Subject>();
        }

        public int Id { get; set; }
        public int Number { get; set; }
        public int Strength { get; set; }

        public virtual ICollection<Subject> Subject { get; set; }
    }
}